# Generated by Django 6.0.4 on 2026-09-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_instance_viecpro",
            "0004_profession_title_person_professions_person_title_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="diverses",
        ),
        migrations.RemoveField(
            model_name="person",
            name="ereignisdatum",
        ),
        migrations.RemoveField(
            model_name="person",
            name="quellenzitat",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="diverses",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="ereignisdatum",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="quellenzitat",
        ),
        migrations.AddField(
            model_name="event",
            name="labels",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="legacy_metainfo_id",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="labels",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="legacy_metainfo_id",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="grouped_into",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grouped",
                to="apis_instance_viecpro.person",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="legacy_metainfo_id",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="texts",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="labels",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="legacy_metainfo_id",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="labels",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="legacy_metainfo_id",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versioninstitution",
            name="labels",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="versioninstitution",
            name="legacy_metainfo_id",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="grouped_into",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_instance_viecpro.person",
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="legacy_metainfo_id",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="texts",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="versionplace",
            name="labels",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="versionplace",
            name="legacy_metainfo_id",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="merged_into",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged",
                to="apis_instance_viecpro.person",
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_instance_viecpro.person",
            ),
        ),
    ]
