# Generated by Django 6.0.4 on 2026-09-17 09:45

import django_json_editor_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_instance_viecpro",
            "0005_remove_person_diverses_remove_person_ereignisdatum_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="labels",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="texts",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="labels",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="texts",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
    ]
