# Generated by Django 6.0.4 on 2026-09-21 06:13

import django_json_editor_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_instance_viecpro",
            "0006_alter_person_labels_alter_person_texts_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="labels",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="labels",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="labels",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="labels",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versioninstitution",
            name="labels",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="labels",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
    ]
