# Generated by Django 6.0.4 on 2026-09-22 09:19

import django.db.models.deletion
import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_instance_viecpro",
            "0007_alter_event_labels_alter_institution_labels_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_death",
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="grouped_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grouped",
                to="apis_instance_viecpro.person",
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="date_of_birth",
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="date_of_death",
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="grouped_into",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_instance_viecpro.person",
            ),
        ),
    ]
